#!/bin/bash

# Copy OpenDKIM config
cp /mail_settings/opendkim.conf /etc/opendkim.conf
cp /mail_settings/mail.private /etc/dkim.key
chown root:root /etc/dkim.key
chmod 600 /etc/dkim.key

ln -sf /dev/stdout /var/log/mail.log
ln -sf /dev/stdout /var/log/mail.info
ln -sf /dev/stdout /var/log/mail.warn
ln -sf /dev/stderr /var/log/mail.err
