#!/bin/bash
domain=$1

>&2 echo "Generating keys for $domain"

>&2 opendkim-genkey -d "$domain"

>&2 echo "Add a TXT domain record with key: \"default._domainkey\" and value:"

>&2 echo "---------"
>&2 echo $(cat default.txt | cut -d "(" -f2 | cut -d ")" -f1 | sed 's/[[:space:]]*//' | sed ':a;N;$!ba;s/\n//g' | sed 's/\"//g')
>&2 echo "---------"

rm default.txt

>&2 echo "Printing a private key: $domain.opendkim_key"
cat default.private

rm default.private
