#!/bin/bash
echo 'Running hostname config'

# Update hostname if present in config
if jq -e '.settings.myhostname?' "$CONFIG_FILE" > /dev/null; then
  echo `jq -r '.settings.myhostname' $CONFIG_FILE` > /etc/mailname
fi
