#!/bin/bash
echo "Running `basename "$0"`"

# Build alias maps
jq -r '.domains | .[] | select(.[0] != null) | .[] | select(has("aliases")) | .email as $email | .aliases | .[] | [., $email] | join("\t")' "$CONFIG_FILE" > /etc/postfix/virtual
# Build domain maps
jq -r '.domains | keys | .[]' "$CONFIG_FILE" > /etc/postfix/virtual-mailbox-domains
# Build mailbox maps
jq -r '.domains | .[] | select(.[0] != null) | .[].email' "$CONFIG_FILE" | sed -e 's|\(.*\)@\(.*\)|\0\t\2/\1/|' > /etc/postfix/virtual-mailbox-maps

# Process alias and mailbox maps
postmap /etc/postfix/virtual
postmap /etc/postfix/virtual-mailbox-maps

# Give postfix ownership of its files
chown -R postfix:postfix /etc/postfix

# Give vmail ownership of all mail folders
chown -R vmail:vmail /vmail
chmod u+w /vmail

# Give vmail ownership of all sieve folders
chown -R vmail:vmail /sieve
chmod u+w /sieve

# Build a password file
jq -r '.domains | .[] | select(.[0] != null) | .[] | [.email, .password] | join(":")' "$CONFIG_FILE" > /etc/dovecot/passwd
