#!/bin/bash
echo "Running `basename "$0"`"

SETTINGS_LOCAL=$MAILMAN_HOME/settings_local.py
MAILMAN_CFG=$MAILMAN_HOME/deployment/mailman.cfg
POSTFIX_LMTP=$MAILMAN_HOME/var/data/postfix_lmtp

# Get secret key from config
secret_key=$(jq -r '.settings | .mailman | .secret_key' "$CONFIG_FILE")

touch 

cat <<EOF > $SETTINGS_LOCAL
# coding=utf-8
import os

VAR_DIR = "$MAILMAN_HOME/var"
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(VAR_DIR, 'mailman-web', 'mailman-web.sqlite'),
    }
}
SECRET_KEY = "$secret_key"
EOF

SMTP_HOST=$(jq '.settings.myhostname' $CONFIG_FILE | sed -e 's/^"//' -e 's/"$//')

MTA_CONFIG_HEADER="# MTA configuration - start"
MTA_CONFIG_FOOTER="# MTA configuration - end"

if grep -q "$MTA_CONFIG_HEADER" "$MAILMAN_CFG"; then
	sed "/$MTA_CONFIG_HEADER/,/$MTA_CONFIG_FOOTER/d" "$MAILMAN_CFG" -i
fi

cat <<EOF >> $MAILMAN_CFG
$MTA_CONFIG_HEADER
[mta]
incoming: mailman.mta.postfix.LMTP
outgoing: mailman.mta.deliver.deliver
lmtp_host: $IP
lmtp_port: 8024
smtp_host: $SMTP_HOST
smtp_port: 25
configuration: python:mailman.config.postfix
$MTA_CONFIG_FOOTER
EOF

# Workaround for Mailman-Client Bug - see https://gitlab.com/mailman/mailmanclient/issues/10
sed -i 's/moderation_reasons=/#moderation_reasons=/' $MAILMAN_HOME/eggs/mailmanclient-1.0.1-py2.7.egg/mailmanclient/_client.py

# IP may have changed .. replace in postfix_lmtp
sed -i "s/\[.*\]/\[$IP\]/g" $POSTFIX_LMTP
postmap $POSTFIX_LMTP